set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind Left
unbind Down
unbind Up
unbind Right

set-option -g default-shell /bin/zsh

set-option -s escape-time 0

set -g window-active-style 'bg=colour232'

set -ag terminal-overrides ',*:cud1=\E[1B'
