#!/bin/bash

nvr_git () {
	local main_module_repo_path=$(git rev-parse --show-superproject-working-tree 2>/dev/null)
	local repo_path=$(git rev-parse --show-toplevel 2>/dev/null)
	if [[ -z "$main_module_repo_path" ]]; then
		main_module_repo_path=$repo_path
	fi

	if [ -n "$main_module_repo_path" ]; then
		local servername=/tmp/nvr$(echo $main_module_repo_path | tr "/" "_")
		nvr -s --servername $servername "$@"
	else
		/usr/bin/nvim "$@"
	fi
}
nvr_git
